### ISSUE TITLE
Meetups about these topics?

### ISSUE THREAD

**Issue by jdnichollsc** [Azure/LearnAI-Bootcamp#14]
Hi guys,
Very interesting material! Exist any meetups about these topics? You guys are welcome in Medellin-Colombia! 👍 

Thanks in advance, Nicholls

**Comment by Rodrigossz** [comment]
OMG, sorry for the huge delay. I manage a lot of repositories and this one was retired years ago. The LearnAI team has not existed since May 2019 and I only found this issue because I'm reviewing the repositories that can be deleted. This content is really good and a lot of people still use it, so I'm going to keep it for now. I'm sure there are many meet-ups in Colombia, but we're based in Redmond. NOTE: I love Bogotá, a beautiful city with impressive cultural richness. Thank you.
