### ISSUE TITLE
Link to setup not working

### ISSUE THREAD

**Issue by robinvdheijden** [Azure/LearnAI-Bootcamp#30]
In the alternative agenda one day bootcamp, the link to 1_Setup in the prerequisites section yields a 404 page not found error.

**Comment by Kaushl2208** [comment]
I can work on it! @heijrova

**Comment by Rodrigossz** [comment]
OMG, sorry for the huge delay. I manage a lot of repositories and this one was retired years ago. The LearnAI team has not existed since May 2019 and I only found this issue because I'm reviewing the repositories that can be deleted. This content is really good and a lot of people still use it, so I'm going to keep it for now. According to the readme file message since MAY/2019: We won't do any maintenance, but I can (i can't guarantee) evaluate fix PRs. TKS!!
